# server
server:
  port: 8080 # http was server port
  servlet: # Server Properties
    context-path: /
    encoding: # Encoding UTF-8
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gtsoft
    password: gtsoft1!
  thymeleaf:
    cache: false
